name: tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  tests-job:
    runs-on: ubuntu-latest
    env:
      GPR_USER: ${{ github.actor }}
      GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'
      - name: run tests
        run:
          echo "GPR_USER=$GPR_USER"
          echo "GPR_TOKEN length=${#GPR_TOKEN}"
          make test
  checkstyle-job:
    needs:
      - tests-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'
      - name: run lint
        run: make lint
